# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hello_world_pb2 as hello__world__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.pong = channel.unary_unary(
        '/helloworld.Greeter/pong',
        request_serializer=hello__world__pb2.HelloRequest.SerializeToString,
        response_deserializer=hello__world__pb2.HelloResponse.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def pong(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'pong': grpc.unary_unary_rpc_method_handler(
          servicer.pong,
          request_deserializer=hello__world__pb2.HelloRequest.FromString,
          response_serializer=hello__world__pb2.HelloResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
